fix: aztec sandbox compose fixes (#3634)
* Make `aztec-sandbox` properly clean up after itself.
* Fix compose file to actually use arguments and not spraff warnings.
* Always mount home dir into containers, nothing else.
* Fix build system r.e. multiarch success tags.
* Fix lying default cli comment.
* Convert all bash shebang lines to use bash from PATH rather than
/usr/bin. Some scripts need bash 4 or above which requires a brew
install on mac.
* Convert noir and downstream containers to be ubuntu, from alpine:
  * Still need to do several others e.g. bb.
  * Alpine has given us several issue, weird threading slowdowns in bb.
  * 10x worse performance in nargo.
  * Slower startup times in node.
* Enough is enough! We can now have a unified development and execution
environment. Lovely.

diff --git a/aztec-up/bin/aztec-sandbox b/aztec-up/bin/aztec-sandbox
--- a/aztec-up/bin/aztec-sandbox
+++ b/aztec-up/bin/aztec-sandbox
@@ -1,11 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -euo pipefail
-
-# Change working dir, so relative volume mounts are in the right place.
-cd ~/.aztec
 
 # Favour 'docker compose', falling back on docker-compose.
 CMD="docker compose"
 $CMD &>/dev/null || CMD="docker-compose"
 
-$CMD -f ~/.aztec/bin/docker-compose.yml up
+ARGS="-f $HOME/.aztec/bin/docker-compose.yml -p sandbox"
+
+# Function to be executed when SIGINT is received.
+cleanup() {
+  $CMD $ARGS down
+}
+
+# Set trap to catch SIGINT and call the cleanup function.
+trap cleanup SIGINT
+
+# Change working dir, so relative volume mounts are in the right place.
+cd ~/.aztec
+
+$CMD $ARGS up --force-recreate --remove-orphans
