feat(ci): use content hash in build system, restrict docs build to *.ts or *.cpp (#1953)
Benefits:
- merges and squashes in your branch don't cause rebuilds
- O(1) tag lookup, no need for tag renaming

Should at least reduce the number of builds by half (stuff that passed
will revalidate quickly on master etc)

diff --git a/build-system/scripts/check_rebuild b/build-system/scripts/check_rebuild
--- a/build-system/scripts/check_rebuild
+++ b/build-system/scripts/check_rebuild
@@ -4,34 +4,18 @@
 # The rebuild patterns are taken from the build manifest (computed from set of dependencies).
 set -euo pipefail
 
-BASE_COMMIT=$1
+TAG=$1
 REPOSITORY=$2
 
 # If given nothing, then exit with failure to rebuild
-[ -n "$BASE_COMMIT" ] || exit 1
+[ -n "$TAG" ] || exit 1
 
-# If a tainted tag exists, remove it exit with failure to rebuild.
-if image_exists $REPOSITORY tainted; then
-  echo "$REPOSITORY has been tainted. Will rebuild."
-  exit 1
-fi
-
-# Compute .rebuild_patterns from the build manifest.
-query_manifest rebuildPatterns $REPOSITORY > .rebuild_patterns
-
-echo "Rebuild patterns:"
-cat .rebuild_patterns
-
-git config diff.renameLimit 999999
-
-# Get list of files that differ
-different_files=$(list_file_diff ${BASE_COMMIT} ${COMMIT_HASH}) || {
-  echo "list_file_diff failed. Rebuild required.";
-  exit 1;
-}
-
-if grep -f .rebuild_patterns <<< "$different_files" &> /dev/null; then
+if ! image_exists $REPOSITORY $TAG; then
   echo "Rebuild required."
+  exit 1
+elif image_exists $REPOSITORY tainted; then
+  # If a tainted tag exists, remove it exit with failure to rebuild.
+  echo "$REPOSITORY has been tainted. Will rebuild."
   exit 1
 else
   echo "No rebuild required."
