chore: Move barretenberg to top of repo. Make circuits build off barretenberg build. (#2221)
This moves barretenberg out of circuits project, to the top level of the
repo, and cleans up a lot of build-system stuff.

## BB and Circuits
* Circuits expects barretenberg to still be where it was before (root of
its repo), but it has a symlink now to the top level.
* Docker scoping is handled by ingesting barretenberg from prior build,
which outputs both the source code, and libraries needed for circuits
(libbarretenberg, libenv, libwasi).
* Circuits not longer builds barretenberg itself.
* barretenberg now does a formatting check over it's code as part of
build. `./format.sh check`
* Remove some refs to openmp in containers as we're phasing it out....
* Remove some cmake around installing barretenberg, as this isn't needed
anymore.

## Build System
* Remove hacks around e2e running locally. Use now official
`cond_run_script` script.
* Remove superfluous scripts and normalise around the
`cond_spot_run_script` and `remote_runner` script.
* `cond_spot_run_build` and `cond_spot_run_test` both implemented in
terms of above.
* Now test runs are handled by `remote_runner` they perform a full
checkout of code and fit in the general pattern of the build system. No
more hacky arbitrary script folder to remote copies.
* Added `yarn-project-base` as dep in `build-manifest.json` to all TS
projects so rebuilds are correctly computed.
* Improved performance of `dependencies` command in `query_manifest` and
also `rebuildPatterns`.
* `query_manifest` outputs absolute paths by default, meaning can remove
various assumptions in other scripts as to current working directory.

diff --git a/build-system/scripts/cond_spot_run_script b/build-system/scripts/cond_spot_run_script
--- a/build-system/scripts/cond_spot_run_script
+++ b/build-system/scripts/cond_spot_run_script
@@ -1,31 +1,34 @@
 #!/bin/bash
-# Conditionally runs a script on a remote spot instance if any dependent code has changed between
-# the last successful run and the present commit.
-#
-# It's expected to be run from the project directory, and that there be a directory called `scripts`
-# containing the given named script to execute on the remote machine.
-#
-# This script is only useful if there is nothing to do in the event there is no rebuild. This is fine
-# for running a suite of tests for example, but is not useful for performing a build, as even if a
-# build has nothing to do, the previous images are retagged with the new commit hash for upstream jobs.
+# Conditionally runs a script on a remote spot instance if the REPOSITORY content hash has changed and we haven't had a
+# successful run.
+# The TAG_POSTFIX is used by cond_spot_run_test whereby we use an image tag postfixed with JOB_NAME to identifify if
+# we need to re-run the job due to prior failures.
 #
 # Arguments are:
 # 1. REPOSITORY: The project repository name in ECR. Used to determine if there are changes since last success.
-# 2. SUCCESS_TAG: To track if this job needs to be run, the repository image is tagged with a prefix after a
-#    successful run. The script will only run if there were relevant code changes since the last successful commit.
-# 3... ARGS: Arguments to pass to spot_run_script.
+# 2. CPUS: Number of cpus on spot request.
+# 3... ARGS: Script and arguments to run.
+#
+# Env vars are:
+# TAG_POSTFIX: Optional. If provided we check for the image tag with this postfix to determine if re-run is required.
 set -eu
 
 REPOSITORY=$1
-shift
-SUCCESS_TAG=$1
-shift
+CPUS=$2
+shift 2
 
 CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
-echo "Content hash tag: cache-$CONTENT_HASH-$SUCCESS_TAG"
+BASE_TAG=cache-$CONTENT_HASH
+SUCCESS_TAG=$BASE_TAG
 
-if ! check_rebuild cache-$CONTENT_HASH-$SUCCESS_TAG $REPOSITORY; then
+if [ -n "${TAG_POSTFIX:-}" ]; then
+  SUCCESS_TAG=$BASE_TAG-$TAG_POSTFIX
+fi
+
+echo "Content hash: $CONTENT_HASH"
+
+if ! check_rebuild $SUCCESS_TAG $REPOSITORY; then
   init_submodules $REPOSITORY
-  spot_run_script $CONTENT_HASH $@
-  retry tag_remote_image $REPOSITORY cache-$CONTENT_HASH cache-$CONTENT_HASH-$SUCCESS_TAG
+  spot_run_script $CONTENT_HASH $CPUS $@
+  retry tag_remote_image $REPOSITORY $BASE_TAG $SUCCESS_TAG
 fi
diff --git a/build-system/scripts/query_manifest b/build-system/scripts/query_manifest
--- a/build-system/scripts/query_manifest
+++ b/build-system/scripts/query_manifest
@@ -3,6 +3,7 @@ set -eu
 CMD=$1
 REPO=$2
 
+ROOT_PATH=${ROOT_PATH:-$PWD}
 MANIFEST=$ROOT_PATH/build_manifest.json
 
 if [ $(jq "has(\"$REPO\")" $MANIFEST) == "false" ]; then
@@ -10,36 +11,65 @@ if [ $(jq "has(\"$REPO\")" $MANIFEST) == "false" ]; then
   exit 1
 fi
 
+function addRebuildPatterns {
+    local TYPE=$(jq -r ".\"$1\".rebuildPatterns | type" $MANIFEST)
+    if [ "$TYPE" == "string" ]; then
+      local FILE=$(jq -r ".\"$1\".rebuildPatterns" $MANIFEST)
+      local BUILD_DIR=$($0 buildDir $1)
+      PATTERNS=(${PATTERNS[@]} $(cat $BUILD_DIR/$FILE))
+    elif [ "$TYPE" == "array" ]; then
+      PATTERNS=(${PATTERNS[@]} $(jq -r ".\"$1\".rebuildPatterns | .[]" $MANIFEST))
+    else
+      >&2 echo "Missing rebuildPatterns property. Either filename as string, or patterns as array."
+      exit 1
+    fi
+}
+
 case "$CMD" in
   dockerfile)
-    jq -r ".\"$REPO\".dockerfile // \"Dockerfile\"" $MANIFEST
+    # In the manifest, the path is relative to buildDir. Return absolute path.
+    BUILD_DIR=$($0 buildDir $REPO)
+    DOCKERFILE=$(jq -r ".\"$REPO\".dockerfile // \"Dockerfile\"" $MANIFEST)
+    echo $BUILD_DIR/$DOCKERFILE
     ;;
   buildDir)
-    jq -r ".\"$REPO\".buildDir" $MANIFEST
+    # In the manifest, the path is relative to the repo root. Return absolute path.
+    BUILD_DIR=$(jq -r ".\"$REPO\".buildDir" $MANIFEST)
+    echo $ROOT_PATH/$BUILD_DIR
     ;;
   projectDir)
+    # In the manifest, the path is relative to the repo root. Return absolute path.
+    PROJECT_DIR=$(jq -r ".\"$REPO\".projectDir // .\"$REPO\".buildDir" $MANIFEST)
+    echo $ROOT_PATH/$PROJECT_DIR
+    ;;
+  relativeProjectDir)
     jq -r ".\"$REPO\".projectDir // .\"$REPO\".buildDir" $MANIFEST
     ;;
   dependencies)
-    ALL_DEPS=()
+    declare -A ALL_DEPS
     add_deps() {
+      if [[ -v ALL_DEPS[$1] ]]; then
+        return
+      fi
+      ALL_DEPS["$1"]=1
       DEPS=($(jq -r ".\"$1\".dependencies // [] | .[]" $MANIFEST))
-      ALL_DEPS=(${ALL_DEPS[@]} ${DEPS[@]})
       for DEP in "${DEPS[@]}"; do
         add_deps $DEP
       done
     }
     add_deps $REPO
-    printf "%s\n" "${ALL_DEPS[@]}" | sort | uniq
+    for KEY in "${!ALL_DEPS[@]}"; do
+      echo $KEY
+    done | sort
     ;;
   rebuildPatterns)
-    ALL_PATTERNS=($(jq -r ".\"$REPO\".rebuildPatterns | .[]" $MANIFEST))
     DEPS=($($0 dependencies $REPO))
+    PATTERNS=()
+    addRebuildPatterns $REPO
     for DEP in "${DEPS[@]}"; do
-      PATTERNS=($(jq -r ".\"$DEP\".rebuildPatterns | .[]" $MANIFEST))
-      ALL_PATTERNS=(${ALL_PATTERNS[@]} ${PATTERNS[@]})
+      addRebuildPatterns $DEP
     done
-    printf "%s\n" "${ALL_PATTERNS[@]}" | sort | uniq
+    printf "%s\n" "${PATTERNS[@]}" | sort | uniq
     ;;
   submodulePath)
     DIR=$($0 buildDir $REPO)
