feat: Noir subrepo. (#3369)
Finally.

Builds the now subrepo'd noir repository. At present this just builds
nargo for x86 and arm, meaning our sandbox install script can now
provide a wrapper `aztec-nargo` that is guaranteed to always be exactly
what we want, regardless of any modifications to macros, compilers,
packages, or whatever. Decouples aztec from being dependent on Noirs
deployment pipeline, while still providing the ability to push changes
back to Noir.

Still need to do work to build npm packages and portal them into
yarn-project. Will do in separate PR.

* Removes old benchmarking stuff and commented canary stuff from
pipeline.
* Adds nargo x86 and arm builds, outputing a multiarch image that also
runs efficiently on macs.
* Removes a load of ARCH specific hack stuff in build-system, in favour
of all cache image URI's now just have their arch appended to their tag.
The arch is determined by the arch of the build system. This required a
small "hack(?)" whereby we will fall back from an unfound arch (arm) to
x86, as we build some of our arm images from previously build x86
images, but i anticipate that'll change at some point.
* Remove some project scripts that bleed the build-system abstraction
(e.g. deploy_docker.sh).
* Introduces `[ci dry-deploy]` commit message command for doing dry run
of deploys. We no longer have conditional workflow filters for
deployment to enable this. I.e. there is always deploy jobs, they just
noop out asap. If dry-deploy is enabled, the deploy jobs will run to
"completion" but doesn't actually execute pushes to dockerhub, and just
runs `npm publish` in dry-run mode.
* Gets rid of `VERSION` files and the sanity check is it got in the way
of the above, and I don't even remember why it was there.
* `build-system` can now launch arm spot instances. This can be
requested e.g. `cond_spot_run_build noir 32 arm64`.
* Added a script to help bootstrap build-instances in case we need to
create new AMI's again in future (I had to create and arm one).
* Deleted some build-system scripts I couldn't see used anywhere.
* `deploy_dockerhub` script now takes list of arches and does the
manifest generation itself.
* Introduces a `should_deploy` script which enables the early out of
deployment jobs. At present this causes exit if there is no COMMIT_TAG.
In future it'll want to run the deploy steps if BRANCH is master as
well.


Follow up PRs will:
* Build NPM packages and portal them into yarn-project.
* Modify sandbox install script to pull noir image, install
`aztec-nargo` wrapper.
* Update vscode plugin to allow selection between global `nargo` or
`aztec-nargo` if both found.
* Someone will do some magic to use the nargo container in github
codespaces so users can press `.` and play.

diff --git a/build-system/scripts/request_spot b/build-system/scripts/request_spot
--- a/build-system/scripts/request_spot
+++ b/build-system/scripts/request_spot
@@ -4,6 +4,7 @@ set -eu
 
 NAME=$1
 CPUS=$2
+ARCH=$3
 
 # Declare an associative array to map CPU counts to instance type suffixes.
 declare -A cpu_map
@@ -29,7 +30,17 @@ if [ -z "$INSTANCE_TYPE_SUFFIX" ]; then
 fi
 
 # Construct the full instance type. We use r6a currently.
-INSTANCE_TYPE="r6a.$INSTANCE_TYPE_SUFFIX"
+if [ "$ARCH" == "x86_64" ]; then
+  MACHINE_TYPE="r6a"
+  AMI="ami-0e5df77ac318c7a18"
+elif [ "$ARCH" == "arm64" ]; then
+  MACHINE_TYPE="r7g"
+  AMI="ami-02c5a5064fe72b22e"
+else
+  echo "Unknown arch: $ARCH"
+  exit 1
+fi
+INSTANCE_TYPE="$MACHINE_TYPE.$INSTANCE_TYPE_SUFFIX"
 
 export AWS_DEFAULT_REGION=us-east-2
 
@@ -38,7 +49,7 @@ PRICE=$(jq -n "$BID_PER_CPU_HOUR*$CPUS*100000 | round / 100000")
 
 launch_spec=$(cat <<EOF
 {
-  "ImageId": "ami-0e5df77ac318c7a18",
+  "ImageId": "$AMI",
   "KeyName": "build-instance",
   "SecurityGroupIds": ["sg-0ccd4e5df0dcca0c9"],
   "InstanceType": "$INSTANCE_TYPE",
@@ -111,10 +122,12 @@ done
 # Wait till ssh port is open.
 >&2 echo "Waiting for SSH at $IP..."
 SECONDS=0
-while ! nc -z -w1 $IP 22; do
+SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-$BUILD_SYSTEM_PATH/remote/ssh_config}
+while ! ssh -F $SSH_CONFIG_PATH -o ConnectTimeout=1 $IP true > /dev/null 2>&1; do
   if (( SECONDS >= 60 )); then
-    >&2 echo "Timeout: SSH port 22 at $IP did not become available after 60 seconds."
+    >&2 echo "Timeout: SSH could not login to $IP within 60 seconds."
     exit 1
   fi
+  sleep 1
 done
 echo $IP
diff --git a/build-system/scripts/setup_env b/build-system/scripts/setup_env
--- a/build-system/scripts/setup_env
+++ b/build-system/scripts/setup_env
@@ -18,8 +18,6 @@ PULL_REQUEST=${6:-}
 BASH_ENV=${BASH_ENV:-}
 BUILD_SYSTEM_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
 PROJECT=$(cat PROJECT)
-VERSION=$(cat VERSION)
-VERSION=${VERSION%% x-release-please-version*}
 COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%s" $COMMIT_HASH)
 
 echo "COMMIT_HASH=$COMMIT_HASH"
@@ -27,41 +25,33 @@ echo "COMMIT_TAG=$COMMIT_TAG"
 echo "JOB_NAME=$JOB_NAME"
 echo "GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL"
 echo "BRANCH=$BRANCH"
+echo "PULL_REQUEST=$PULL_REQUEST"
+
+# If the user has requested to perform a "dry deploy", we set the commit tag to fake version, and set DRY_DEPLOY to 1.
+if [[ "$COMMIT_MESSAGE" == *"[ci dry-deploy]"* ]]; then
+  COMMIT_TAG=v999.999.999
+  DRY_DEPLOY=1
+fi
 
 if [ -n "${COMMIT_TAG:-}" ]; then
-  # We're tagged e.g. v2.1.123 or v2.1.123-testnet.0.
-  # First we sanity check that the tag matches the VERSION file.
-  echo "Extracting commit tag version..."
-  # Strips the e.g. '-testnet.XX' from the COMMIT_TAG
-  WITHOUT_VERSION_TAG=${COMMIT_TAG%%-*}
-  # Strips the subversion, leaving just the 'vMAJ.MIN' e.g. v2.1
-  COMMIT_TAG_VERSION=${WITHOUT_VERSION_TAG%.*}
-  echo "WITHOUT_VERSION_TAG=$WITHOUT_VERSION_TAG"
-  echo "COMMIT_TAG_VERSION=$COMMIT_TAG_VERSION"
-  # COMMIT_TAG_VERSION=$(echo "$COMMIT_TAG" | grep -oE "v\d+.\d+")
-  if [ "$COMMIT_TAG" != "$VERSION" ]; then
-    echo "Commit tag $COMMIT_TAG does not match repo version $VERSION."
-    exit 1
-  fi
-
-  # Extract the version tag from the commit tag, if it has one, e.g. testnet.
+  # Extract the deploy env from the commit tag, if it has one, e.g. testnet.
   # If we have one, we look something like v2.1.123-testnet.0. This is a "non production" release.
   if [[ "$COMMIT_TAG" == *"-"* ]]; then
     # Strips the trailing '.XX' from the end of the commit tag
     TEMP=${COMMIT_TAG%.*}
     # Strips the 'vX.Y.ZZZ-' from the front of the commit tag, leaving the e.g. 'testnet'
-    VERSION_TAG=${TEMP##*-}
+    DEPLOY_ENV=${TEMP##*-}
   else
-    VERSION_TAG=prod
+    DEPLOY_ENV=prod
   fi
 else
-  # We have no commit tag. Check this is our staging branch, otherwise use dev.
-  [[ $BRANCH = "stage" ]] && VERSION_TAG="stage" || VERSION_TAG="dev"
+  # We have no commit tag, this is our devnet.
+  DEPLOY_ENV="dev"
 fi
 
-# - The deploy tag (used in api paths, subdomains), is a concatenation of the project name and version tag,
-#   e.g. aztec-connect-dev, aztec-connect-testnet, or aztec-connect-prod
-DEPLOY_TAG=$PROJECT-$VERSION_TAG
+# - The deploy tag (used in api paths, subdomains), is a concatenation of the project name and deploy environment,
+#   e.g. aztec-dev, aztec-testnet, or aztec-prod
+DEPLOY_TAG=$PROJECT-$DEPLOY_ENV
 
 if [ -z "$BASH_ENV" ]; then
   BASH_ENV=$(mktemp)
@@ -70,6 +60,7 @@ fi
 echo export ROOT_PATH=$PWD >> $BASH_ENV
 echo export BUILD_SYSTEM_PATH=$BUILD_SYSTEM_PATH >> $BASH_ENV
 echo export DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} >> $BASH_ENV
+echo export BUILDKIT_PROGRESS=plain >> $BASH_ENV
 echo export SSH_CONFIG_PATH=$BUILD_SYSTEM_PATH/remote/ssh_config >> $BASH_ENV
 echo export PATH=\$PATH:$BUILD_SYSTEM_PATH/scripts >> $BASH_ENV
 echo export AWS_DEFAULT_REGION=eu-west-2 >> $BASH_ENV
@@ -86,14 +77,22 @@ echo export COMMIT_TAG=$COMMIT_TAG >> $BASH_ENV
 echo "export COMMIT_MESSAGE='${COMMIT_MESSAGE//\'/\'\\\'\'}'" >> $BASH_ENV
 echo export JOB_NAME=$JOB_NAME >> $BASH_ENV
 echo export GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL >> $BASH_ENV
-echo export VERSION_TAG=$VERSION_TAG >> $BASH_ENV
+echo export DEPLOY_ENV=$DEPLOY_ENV >> $BASH_ENV
 echo export DEPLOY_TAG=$DEPLOY_TAG >> $BASH_ENV
 echo export BRANCH=$BRANCH >> $BASH_ENV
 echo export PULL_REQUEST=$PULL_REQUEST >> $BASH_ENV
+echo export DRY_DEPLOY=${DRY_DEPLOY:-} >> $BASH_ENV
+# We want very strict failures on any failing command, undefined variable, or commands that pipe to other commands.
+echo set -euo pipefail >> $BASH_ENV
+# Enable logging if [ci debug] is in commit message.
+if [[ "$COMMIT_MESSAGE" == *"[ci debug]"* ]]; then
+  echo export BUILD_SYSTEM_DEBUG=1 >> $BASH_ENV
+  echo set -x >> $BASH_ENV
+fi
 
 # Only run the following if we're the result of a commit (i.e. not being run manually).
 if [ -n "$COMMIT_HASH" ]; then
-  # Our alpine build image has yq installed, ubuntu build instances download from github.
+  # Our alpine build image has yq installed, ubuntu build instances install from gzips in ../bin.
   if [ ! -f /etc/alpine-release ]; then
     BIN_PATH=$BUILD_SYSTEM_PATH/bin
     echo export PATH=$BIN_PATH:\$PATH >> $BASH_ENV
