chore: bootstrap improvements. (#4711)
* `l1-contracts` cli cache bootstrappable.
* `noir-contracts` cli cache bootstrappable.
* `bootstrap.sh` will always attempt to pull from cli cache if the user
has docker and aws-credentials.
* `bootstrap.sh full` will skip trying to use the cache.
* `avm-transpiler` builds on focal for better compatability.
* New script `remove_old_images` removes all docker images for a repo,
older than the current content hash. Prevents local disk usage
explosion. Called both after bootstrapping from cache, and as part of
`bootstrap_docker.sh`.
* Reduced `retry` from 10s to 5s. Can be disabled with
`RETRY_DISABLED=1` env var.

diff --git a/build-system/scripts/retry b/build-system/scripts/retry
--- a/build-system/scripts/retry
+++ b/build-system/scripts/retry
@@ -1,7 +1,13 @@
+if [ -n "${RETRY_DISABLED:-}" ]; then
+    "$@" && exit || exit 1
+fi
+
 ATTEMPTS=3
-# Retries up to 3 times with 10 second intervals
+# Retries up to 3 times with 5 second intervals
 for i in $(seq 1 $ATTEMPTS); do
-    "$@" && exit || sleep 10
+    "$@" && exit
+    [ "$i" != "$ATTEMPTS" ] && sleep 5
 done
+
 >&2 echo "$@ failed after $ATTEMPTS attempts"
 exit 1
