fix: retry request spot (#3116)
I've seen some jobs failing silently around starting spot instances.
I've seen some network errors around manifest stuff.

This may not fix the first issue. But it does introduce a little extra
logging that might give an idea of whats failing. It will retry the
spinning up of the instance if it fails, but im not convinced that was
what was failing.

This adds retries to the manifest stuff.

diff --git a/build-system/scripts/retry b/build-system/scripts/retry
--- a/build-system/scripts/retry
+++ b/build-system/scripts/retry
@@ -3,5 +3,5 @@ ATTEMPTS=3
 for i in $(seq 1 $ATTEMPTS); do
     "$@" && exit || sleep 10
 done
-echo "$@ failed after $ATTEMPTS attempts"
+>&2 echo "$@ failed after $ATTEMPTS attempts"
 exit 1
diff --git a/build-system/scripts/spot_run_script b/build-system/scripts/spot_run_script
--- a/build-system/scripts/spot_run_script
+++ b/build-system/scripts/spot_run_script
@@ -12,26 +12,31 @@ CONTENT_HASH=$1
 CPUS=$2
 shift 2
 
-# On any sort of exit (error or not), kill spot request so it doesn't count against quota.
+# On any sort of exit (error or not).
 function on_exit {
+    set +e
+
+    if [ -n "$IP" ]; then
+        echo "Terminating spot instance..."
+        ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1
+    fi
+
+    # Kill spot request so it doesn't count against quota.
     if [ -f "sir-$CONTENT_HASH:$JOB_NAME.txt" ]; then
         SIR=$(cat sir-$CONTENT_HASH:$JOB_NAME.txt)
-        echo "Cancelling spot instance request $SIR (silently)"
+        echo "Cancelling spot instance request $SIR..."
         aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SIR >/dev/null 2>&1 || true
     fi
 }
 trap on_exit EXIT
 
 # Get spot instance.
-IP=$(request_spot $CONTENT_HASH:$JOB_NAME $CPUS)
+IP=$(retry request_spot $CONTENT_HASH:$JOB_NAME $CPUS)
+
+if [ -z "$IP" ]; then
+    echo "Failed to get spot instance."
+    exit 1
+fi
 
 # Run script remotely on spot instance, capturing success or failure.
-set +e
 remote_run_script $IP $@
-CODE=$?
-
-# Shutdown spot.
-echo "Terminating spot instance..."
-ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1
-
-exit $CODE
