chore(ci): Clean up stale image tags (#1818)
Attempt at cleaning up image tags when a tag operation fails due to
limit exceeded. The `clean_image_tags` loops over all image tags that
look like a commit, and check if the commit is anywhere in git. If it
isn't, it's because it belongs to a branch that got deleted (most
likely, a PR that was merged) and we can safely kill it.

We can still theoretically hit the 1000 limit in this scenario, but I
think it's a lot less likely. A local test run of the script showed that
most image tags correspond to non-existing commits.

diff --git a/build-system/scripts/tag_remote_image b/build-system/scripts/tag_remote_image
--- a/build-system/scripts/tag_remote_image
+++ b/build-system/scripts/tag_remote_image
@@ -27,9 +27,22 @@ NEW_TAG_MANIFEST=$(aws ecr batch-get-image \
 
 if [ "$EXISTING_TAG_MANIFEST" != "$NEW_TAG_MANIFEST" ]; then
   echo "Tagging $1:$EXISTING_TAG as $1:$NEW_TAG..."
-  aws ecr put-image \
+  TAG_RESULT=$(aws ecr put-image \
     --region $REGION \
     --repository-name $REPOSITORY \
     --image-tag $NEW_TAG \
-    --image-manifest "$EXISTING_TAG_MANIFEST" > /dev/null 2>&1
+    --image-manifest "$EXISTING_TAG_MANIFEST" 2>&1)
+  TAG_EXIT_CODE=$?
+  
+  # If we failed to tag due to too many tags on this image, then clean some of them up and try again
+  if [ $TAG_EXIT_CODE -ne 0 ] && $(echo $TAG_RESULT | grep -q LimitExceededException); then
+    echo "Failed to tag due to limit exceeded. Starting tag cleanup."
+    clean_image_tags $REPOSITORY $EXISTING_TAG $REGION
+
+    aws ecr put-image \
+      --region $REGION \
+      --repository-name $REPOSITORY \
+      --image-tag $NEW_TAG \
+      --image-manifest "$EXISTING_TAG_MANIFEST"
+  fi
 fi
