fix: Pw/update merge check (#6201)
Please read [contributing guidelines](CONTRIBUTING.md) and remove this
line.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -448,30 +448,6 @@ jobs:
   merge-check:
     runs-on: ubuntu-latest
     needs:
-      - e2e
-      - bb-native-tests
-      - bb-bench
-      - yarn-project-formatting
-      - yarn-project-test
-      - prover-client-test
-      - noir-packages-test
-      - noir-test
-    if: always()
-    steps:
-      - run: |
-          echo "e2e status: ${{ needs.e2e.result }}"
-          echo "bb-native-tests status: ${{ needs.bb-native-tests.result }}"
-          echo "bb-bench status: ${{ needs.bb-bench.result }}"
-          echo "yarn-project-formatting status: ${{ needs.yarn-project-formatting.result }}"
-          echo "yarn-project-test status: ${{ needs.yarn-project-test.result }}"
-          if [[ "${{ needs.e2e.result }}" != 'success' || "${{ needs.bb-native-tests.result }}" != 'success' || "${{ needs.bb-bench.result }}" != 'success' || "${{ needs.yarn-project-formatting.result }}" != 'success' || "${{ needs.yarn-project-test.result }}" != 'success' ]]; then
-            echo "Pull request merging not allowed due to failures."
-            exit 1
-          fi
-          echo "Pull request merging now allowed."
-
-  notify:
-    needs:
       [
         e2e,
         bb-native-tests,
@@ -479,7 +455,27 @@ jobs:
         yarn-project-formatting,
         yarn-project-test,
         prover-client-test,
+        bb-js-test,
+        barretenberg-acir-tests-bb-js,
+        barretenberg-acir-tests-bb,
+        barretenberg-acir-tests-sol,
+        noir-test,
+        noir-packages-test,
       ]
+    if: always()
+    steps:
+      - run: |
+          failed=${{ contains(needs.*.result, 'failure') }}
+          if $failed
+          then
+            echo "At least one job failed, merging not allowed."
+            exit 1
+          fi
+          echo "All jobs succeeded, merge allowed."
+
+  notify:
+    needs:
+      - merge-check
     runs-on: ubuntu-latest
     if: ${{ github.ref == 'refs/heads/master' && failure() }}
     steps:
