chore(ci): merge-check fixes (#6485)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -479,6 +479,8 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - setup
+      # - bench-e2e # does not block merge
+      # - bench-summary # does not block merge
       - e2e
       - bb-native-tests
       - acir-bench
@@ -491,17 +493,25 @@ jobs:
       - barretenberg-acir-tests-bb
       - barretenberg-acir-tests-sol
       - noir-test
+      - noir-projects
+      - l1-contracts-test
       - noir-packages-test
+      - docs-preview
+      # - protocol-circuit-gates-report # does not block merge
     if: always()
     steps:
-      - run: |
-          failed=${{ contains(needs.*.result, 'failure') }}
-          if $failed
-          then
-            echo "At least one job failed, merging not allowed."
-            exit 1
+      - name: Report overall success
+        env:
+          # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+          FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          if [[ $FAIL == true ]]; then
+              echo "At least one job failed (or skipped/cancelled), merging not allowed."
+              exit 1
+          else
+              echo "All jobs succeeded, merge allowed."
+              exit 0
           fi
-          echo "All jobs succeeded, merge allowed."
 
   notify:
     needs:
