asdfasdf

diff --git a/.github/workflows/docker-test-flow.yml b/.github/workflows/docker-test-flow.yml
--- a/.github/workflows/docker-test-flow.yml
+++ b/.github/workflows/docker-test-flow.yml
@@ -624,76 +624,84 @@ jobs:
         run: |
           /usr/src/noir/.github/scripts/noir-codegen-test.sh
 
-  # test-integration:
-  #   name: integration test
-  #   runs-on: ubuntu-latest
-  #   needs: [build-base-js, artifact-nargo, test-noir-wasm, test-noirc-abi, test-acvm_js,  build-noir-js-types, test-noir_js]
-  #   container:
-  #     image: ghcr.io/noir-lang/noir:${{ github.sha }}-js
-  #     credentials:
-  #       username: ${{ github.actor }}
-  #       password: ${{ secrets.github_token }}
-  #   steps:
-  #     - name: download nargo
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: nargo
-  #         path: /usr/src/noir/target/release
-  #     - name: prep downloaded artifact
-  #       run: |
-  #         chmod +x /usr/src/noir/target/release/nargo
-  #     - name: Upload artifact
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: noir_wasm
-  #         path: /usr/src/noir/compiler/wasm/outputs/out/noir_wasm
-  #     - name: Download noirc_abi package artifact
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: noirc_abi_wasm
-  #         path: /usr/src/noir/tooling/noirc_abi_wasm
-  #     - name: Download acvm_js package artifact
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: acvm_js
-  #         path: /usr/src/noir/acvm-repo/acvm_js
-  #     - name: Download noir js types
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: noir-js-types
-  #         path: |
-  #           /usr/src/noir/tooling/noir_js_types/lib
-  #     - name: Download noir js
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: noir_js
-  #         path:
-  #           /usr/src/noir/tooling/noir_js/lib
-  #     - name: test
-  #       run: |
-  #         /usr/src/noir/.github/scripts/test-noir-codegen.sh
+  test-integration:
+    name: integration test
+    runs-on: ubuntu-latest
+    needs: [build-base-js, artifact-nargo, test-noir-wasm, build-noirc-abi, test-acvm_js,  build-noir-js-types, build-noir_js, build-barretenberg-backend]
+    container:
+      image: ghcr.io/noir-lang/noir:${{ github.sha }}-js
+      credentials:
+        username: ${{ github.actor }}
+        password: ${{ secrets.github_token }}
+    steps:
+      - name: download nargo
+        uses: actions/download-artifact@v4
+        with:
+          name: nargo
+          path: /usr/src/noir/target/release
+      - name: prep downloaded artifact
+        run: |
+          chmod +x /usr/src/noir/target/release/nargo
+      - name: Upload artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: noir_wasm
+          path: /usr/src/noir/compiler/wasm/outputs/out/noir_wasm
+      - name: Download noirc_abi package artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: noirc_abi_wasm
+          path: /usr/src/noir/tooling/noirc_abi_wasm
+      - name: Download acvm_js package artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: acvm_js
+          path: /usr/src/noir/acvm-repo/acvm_js
+      - name: Download noir js types
+        uses: actions/download-artifact@v4
+        with:
+          name: noir-js-types
+          path: |
+            /usr/src/noir/tooling/noir_js_types/lib
+      - name: Download noir js
+        uses: actions/download-artifact@v4
+        with:
+          name: noir_js
+          path:
+            /usr/src/noir/tooling/noir_js/lib
+      - name: download backend barretenberg
+        uses: actions/download-artifact@v4
+        with:
+          name: barretenberg-backend
+          path:
+            /usr/src/noir/tooling/noir_js_backend_barretenberg/lib
+      - name: test
+        run: |
+          cd /usr/src/noir
+          npx playwright install && npx playwright install-deps
+          yarn workspace integration-tests test
 
-  # tests-end:
-  #   name: End
-  #   runs-on: ubuntu-latest
-  #   if: ${{ always() }}
-  #   needs: 
-  #     - test-nargo
-  #     - test-noirc-abi
-  #     - test-noir-wasm
-  #     - test-integration
-  #     - test-noir_codegen
-  #     - test-acvm_js
-  #     - test-barretenberg-backend
-  #     - test-noir_js
+  tests-end:
+    name: End
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs: 
+      - test-nargo
+      - test-noirc-abi
+      - test-noir-wasm
+      - test-integration
+      - test-noir_codegen
+      - test-acvm_js
+      - test-barretenberg-backend
+      - test-noir_js
     
-  #   steps:
-  #       - name: Report overall success
-  #         run: |
-  #           if [[ $FAIL == true ]]; then
-  #               exit 1
-  #           else
-  #               exit 0
-  #           fi
-  #         env:
-  #           FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
+    steps:
+        - name: Report overall success
+          run: |
+            if [[ $FAIL == true ]]; then
+                exit 1
+            else
+                exit 0
+            fi
+          env:
+            FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
