asdf

diff --git a/.github/workflows/docker-test-flow.yml b/.github/workflows/docker-test-flow.yml
--- a/.github/workflows/docker-test-flow.yml
+++ b/.github/workflows/docker-test-flow.yml
@@ -431,3 +431,26 @@ jobs:
       - name: test
         run: |
           /usr/src/noir/.github/scripts/test-noir-codegen.sh
+
+  tests-end:
+    name: End
+    runs-on: ubuntu-latest
+    # We want this job to always run (even if the dependant jobs fail) as we want this job to fail rather than skipping.
+    if: ${{ always() }}
+    needs: 
+      - test-noirc-abi
+      - test-source-resolver
+      - test-noir-wasm
+      - test-integration
+    
+    steps:
+        - name: Report overall success
+          run: |
+            if [[ $FAIL == true ]]; then
+                exit 1
+            else
+                exit 0
+            fi
+          env:
+            # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+            FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
