chore(ci): add warning sticky comment

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -100,6 +100,36 @@ jobs:
           git commit -m "chore(docs): cut new docs version for tag ${{ steps.noir-version.outputs.semver }}"
           git push
 
+  release-end:
+    name: Release End
+    runs-on: ubuntu-latest
+    # We want this job to always run (even if the dependant jobs fail) as we need apply changes to the sticky comment.
+    if: ${{ always() }}
+    
+    needs:
+      - update-acvm-workspace-package-versions
+      - update-docs
+
+    env:
+      # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+      FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }
+
+    steps:  
+      - name: Add warning to sticky comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          # delete the comment in case failures have been fixed
+          delete: ${{ !env.FAIL }}
+          message: "The release workflow has not completed successfully. Releasing now will result in a broken release"
+
+      - name: Report overall success
+        run: |
+          if [[ $FAIL == true ]]; then
+              exit 1
+          else
+              exit 0
+          fi
+
   build-binaries:
     name: Build binaries
     needs: [release-please]
