.

diff --git a/.github/workflows/reports.yml b/.github/workflows/reports.yml
--- a/.github/workflows/reports.yml
+++ b/.github/workflows/reports.yml
@@ -391,6 +391,31 @@ jobs:
           retention-days: 3
           overwrite: true
 
+      - name: Check compilation time limit
+        run: |
+          TIME=$(jq '.[0].value' ${{ steps.compilation_report.outputs.report_path }})
+          TIME_LIMIT=${{ matrix.compilation-timeout }}
+          if awk 'BEGIN{exit !(ARGV[1]>ARGV[2])}' "$TIME" "$TIME_LIMIT"; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            echo "Failing due to compilation exceeding timeout..."
+            echo "Timeout: "$TIME_LIMIT"s"
+            echo "Compilation took: "$TIME"s".
+            exit 1
+          fi
+
+      - name: Check execution time limit
+        if: ${{ !matrix.cannot_execute }}
+        run: |
+          TIME=$(jq '.[0].value' ${{ steps.execution_report.outputs.report_path }})
+          TIME_LIMIT=${{ matrix.execution-timeout }}
+          if awk 'BEGIN{exit !(ARGV[1]>ARGV[2])}' "$TIME" "$TIME_LIMIT"; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            echo "Failing due to execution exceeding timeout..."
+            echo "Timeout: "$TIME_LIMIT"s"
+            echo "Execution took: "$TIME"s".
+            exit 1
+          fi
+
   external_repo_memory_report:
     needs: [build-nargo, benchmark-projects-list]
     runs-on: ubuntu-22.04
