chore: add timeouts to reports CI

diff --git a/.github/workflows/reports.yml b/.github/workflows/reports.yml
--- a/.github/workflows/reports.yml
+++ b/.github/workflows/reports.yml
@@ -327,6 +327,22 @@ jobs:
           mv /home/runner/work/noir/noir/scripts/test_programs/parse_time.sh ./parse_time.sh
           ./execution_report.sh 1 ${{ matrix.project.num_runs }}
 
+      - name: Check compilation time limit
+        run: |
+          TIME=$(jq '.value' ./test-repo/${{ matrix.project.path }}/compilation_report.json)
+          if [ "$TIME" -gt "80" ]; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            exit 1
+          fi
+
+      - name: Check execution time limit
+        run: |
+          TIME=$(jq '.value' ./test-repo/${{ matrix.project.path }}/execution_report.json)
+          if [ "$TIME" -gt "60" ]; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            exit 1
+          fi
+
       - name: Move compilation report
         id: compilation_report
         shell: bash
@@ -422,6 +438,14 @@ jobs:
         run: |
           ./memory_report.sh 1 1
 
+      - name: Check compilation memory limit
+        run: |
+          MEMORY=$(jq '.value' ./test-repo/${{ matrix.project.path }}/compilation_memory_report.json)
+          if [ "$MEMORY" -gt "6000" ]; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            exit 1
+          fi
+
       - name: Move compilation report
         id: compilation_mem_report
         shell: bash
@@ -439,10 +463,18 @@ jobs:
           retention-days: 3
           overwrite: true
 
+      - name: Check execution memory limit
+        if: ${{ !matrix.project.cannot_execute }}
+        run: |
+          MEMORY=$(jq '.value' ./memory_report.sh)
+          if [ "$MEMORY" -gt "1000" ]; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            exit 1
+          fi
+
       - name: Move execution report
         id: execution_mem_report
         if: ${{ !matrix.project.cannot_execute }}
-        shell: bash
         run: |
           PACKAGE_NAME=${{ matrix.project.path }}
           PACKAGE_NAME=$(basename $PACKAGE_NAME)
@@ -493,7 +525,6 @@ jobs:
           jq --slurp '. | flatten' ./reports/* | tee time_bench.json
 
       - name: Store benchmark result
-        continue-on-error: true
         uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29
         with:
           name: "Compilation Time"
@@ -543,7 +574,6 @@ jobs:
           jq --slurp '. | flatten' ./reports/* | tee memory_bench.json
 
       - name: Store benchmark result
-        continue-on-error: true
         uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29
         with:
           name: "Compilation Memory"
@@ -593,7 +623,6 @@ jobs:
           jq --slurp '. | flatten' ./reports/* | tee memory_bench.json
 
       - name: Store benchmark result
-        continue-on-error: true
         uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29
         with:
           name: "Execution Memory"
@@ -644,7 +673,6 @@ jobs:
           jq --slurp '. | flatten' ./reports/* | tee time_bench.json
 
       - name: Store benchmark result
-        continue-on-error: true
         uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29
         with:
           name: "Execution Time"
@@ -658,3 +686,28 @@ jobs:
           fail-on-alert: false
           alert-comment-cc-users: "@TomAFrench"
           max-items-in-chart: 50
+
+  # This is a job which depends on all test jobs and reports the overall status.
+  # This allows us to add/remove test jobs without having to update the required workflows.
+  reports-end:
+    name: End
+    runs-on: ubuntu-22.04
+    # We want this job to always run (even if the dependant jobs fail) as we want this job to fail rather than skipping.
+    if: ${{ always() }}
+    needs:
+      - upload_compilation_report
+      - upload_compilation_memory_report
+      - upload_execution_report
+      - upload_execution_memory_report
+     
+    steps:
+        - name: Report overall success
+          run: |
+            if [[ $FAIL == true ]]; then
+                exit 1
+            else
+                exit 0
+            fi
+          env:
+            # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+            FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
