Check that command fails

diff --git a/.github/workflows/test-js-packages.yml b/.github/workflows/test-js-packages.yml
--- a/.github/workflows/test-js-packages.yml
+++ b/.github/workflows/test-js-packages.yml
@@ -643,7 +643,13 @@ jobs:
 
       - name: Run nargo compile
         working-directory: ./test-repo/noir-projects/noir-contracts
-        run: nargo compile --inliner-aggressiveness 0
+        run: |
+          if nargo compile --inliner-aggressiveness 0; then
+            echo "Expected compile-noir-contracts to fail but it didn't. Please update the workflow to assert that the command now does not fail."
+            exit 1
+          else
+            exit 0
+          fi
 
   upload_critical_library_report:
     name: Upload critical library report
@@ -709,8 +715,7 @@ jobs:
       - test-integration-node
       - test-integration-browser
       - test-examples
-      # TODO: uncomment when it starts passing again
-      # - compile-noir-contracts
+      - compile-noir-contracts
 
     steps:
         - name: Report overall success
