chore: simplify reports

diff --git a/.github/workflows/test-js-packages.yml b/.github/workflows/test-js-packages.yml
--- a/.github/workflows/test-js-packages.yml
+++ b/.github/workflows/test-js-packages.yml
@@ -541,17 +541,6 @@ jobs:
           fi
         env:
           NARGO_IGNORE_TEST_FAILURES_FROM_FOREIGN_CALLS: true
-      
-      - name: Check test time limit
-        run: |
-          TIME=$(jq '.[0].value' ./test-repo/${{ matrix.path }}/${{ steps.test_report.outputs.test_report_name }}.json)
-          if awk 'BEGIN{exit !(ARGV[1]>ARGV[2])}' "$TIME" "${{ matrix.timeout }}"; then
-            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
-            echo "Failing due to test suite exceeding timeout..."
-            echo "Timeout: ${{ matrix.timeout }}"
-            echo "Test suite took: $TIME".
-            exit 1
-          fi
 
       - name: Compare test results
         working-directory: ./noir-repo
@@ -565,6 +554,17 @@ jobs:
           path: ./test-repo/${{ matrix.path }}/${{ steps.test_report.outputs.test_report_name }}.json
           retention-days: 3
           overwrite: true
+
+      - name: Check test time limit
+        run: |
+          TIME=$(jq '.[0].value' ./test-repo/${{ matrix.path }}/${{ steps.test_report.outputs.test_report_name }}.json)
+          if awk 'BEGIN{exit !(ARGV[1]>ARGV[2])}' "$TIME" "${{ matrix.timeout }}"; then
+            # Don't bump this timeout without understanding why this has happened and confirming that you're not the cause.
+            echo "Failing due to test suite exceeding timeout..."
+            echo "Timeout: ${{ matrix.timeout }}"
+            echo "Test suite took: $TIME".
+            exit 1
+          fi
 
   compile-noir-contracts:
     needs: [build-nargo]
