Revert build stage

diff --git a/.github/workflows/wasm.yml b/.github/workflows/wasm.yml
--- a/.github/workflows/wasm.yml
+++ b/.github/workflows/wasm.yml
@@ -21,8 +21,20 @@ jobs:
           nix_path: nixpkgs=channel:nixos-22.11
           github_access_token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build wasm package
-        run: nix build .#packages.wasm || true
+      - name: Build noir_wasm with Nix flakes
+        run: |
+          nix build .#wasm || true
+          echo "Build result:"
+          ls -la result/pkg
+
+      - name: Print build.log if build failed
+        run: |
+          if [ -d result ]; then
+            echo "Build successful."
+          else
+            echo "Build failed. Printing build.log:"
+            cat crates/wasm/build.log || true
+          fi
 
       # - name: Build wasm package
       #     run: nix build .#packages.wasm --keep-failed
